### PR TITLE
Feature/7 assign worker to event

### LINKED ISSUE #7: Assign worker to event
Create API which will assign one worker to an event.

To be discuss: send 1 worker at a time to backend OR send multiple instances.

EST 8

### PR DESCRIPTION
**Pull request by luxz97**
Closes #7.

### CODE REVIEW

**Review by akosgdcsi — APPROVED** [review]

**Review by pop-simon — CHANGES_REQUESTED** [review]
Please consider changing the following
--

- Initialize the `ICollection<WorkEvent> WorkEvents` in the constructor of **Label.cs** and **Pictures.cs**
- Initialize the `ICollection<WmanUserRole> UserRoles` in the constructor of **WmanUser.cs**
- Initialize the `ICollection<Label> Labels` and `ICollection<Pictures> ProofOfWorkPic` in the constructor of **WorkEvent.cs**
- _Bonus_: I know it is not that issue but the `WorkEventRepo.GetAll()` method returns `null` values as `Address`. If you have the time please update the method like this `return this.db.WorkEvent.AsNoTracking().Include(x => x.Address);`. It will fill the empty `Address` values. [HELP](https://blog.jetbrains.com/dotnet/2021/02/24/entity-framework-core-5-pitfalls-to-avoid-and-ideas-to-try/)

**Next time you want to refactor the code like you did, contact Peti or me before making these changes.** We already discussed this but I would like to highlight it again

Otherwise it is a good job 🏆

**Review by pop-simon — APPROVED** [review]

**Review by tsaskater — CHANGES_REQUESTED** [review]
What does the JobOfUser endpoint do?
Why is it in the auth logic?
Why does it only return Ids? The frontend can not use single id-s for anything.
The assign features does not work. Simon helped me out with debugging your code.
The update method contains AsNoTracking() which is good, but it messes up the assignment.
Simon found a possible solution for you→
Create another private method called GetOneForUpdate.
Do not use AsNoTracking in this method.
@akosgdcsi  you should expect the same problem coming up in other issues.
Please fix the issue. Next time, please do not submit a pull request until you try out your endpoints.

**Comment by luxz97** [comment]
@tsaskater 
> What does the JobOfUser endpoint do?

I'll assume you mean the `getAssignedJobsOfUser(string username)` endpoint. I believe the endpoint documentation is self-explanatory. It returns a  collection of the "jobs" assigned to a selected user. I do agree, the word choice "job" wasn't the best, as we've been dealing with "workevents" before, but it was close enough imo.

> Why is it in the auth logic?

Valid question, wasn't sure about this one. My line of thinking is that it was related to user management, and auth logic was the closest to it, and creating a new logic/controllers just for this would clutter the project. My suggestion would be to keep it here, and if later down the line more user management related functions will be needed, then refactor it into separate classes. But if you still would like it moved, please let me know. 

> Why does it only return Ids? The frontend can not use single id-s for anything.

I believe this is what you asked for. I wanted to return a dto here. (`/DTO_Models/AssignedEventDTO.cs`) 
7c22ab0197eb04308ea6d90f5b677c709469644a

Edit: After giving it some thought, I probably misinterpreted what you meant with this.

> The assign features does not work. 
>  ..Next time, please do not submit a pull request until you try out your endpoints.

FIx will be coming up later today. Every endpoint was tested, and worked in the initial state of the pr, they broke when I implemented Simon's last request, which contained the .asnotracking(). Didn't re-test every endpoint, only the ones I tought were affected by the new inclusion of the nested `address` object.

**Review by pop-simon — CHANGES_REQUESTED** [review]
> Didn't re-test every endpoint, only the ones I tought were affected by the new inclusion of the nested address object.

You did not test the ones that were affected. The `async Task<WorkEvent> GetOne(int key)` method is used by the `async Task Update(int oldKey, WorkEvent element)` so it was affected by the modification. Furthermore you **should not** just use something new without understanding it. If you read the `AsNoTracking()` description (hover the cursor on the method in VS) then you could realize it returns values that are read-only.

> Create another private method called GetOneForUpdate.
> Do not use AsNoTracking in this method.

Peti requested this because the solution is that simple:
```
public async Task Update(int oldKey, WorkEvent element)
{
    var oldWorkEvent = await GetOneForUpdate(oldKey);
    oldWorkEvent.JobDescription = element.JobDescription;
    oldWorkEvent.EstimatedStartDate = element.EstimatedStartDate;
    oldWorkEvent.EstimatedFinishDate = element.EstimatedFinishDate;
    oldWorkEvent.AssignedUsers = element.AssignedUsers;
    await this.db.SaveChangesAsync();
}

private async Task<WorkEvent> GetOneForUpdate(int key)
{
    var entity = await (from x in db.WorkEvent
                        where x.Id == key
                        select x).Include(x => x.AssignedUsers).Include(x => x.Address).FirstOrDefaultAsync();
    return entity;
}
```

In contrast you created a new public method, extended the interface and use two `GetOne(int key)` method globally.
The same applies to `AuthLogic`.

**Comment by luxz97** [comment]
Unfortunatelly I could not make it in the requested form, spent the better part of the day trying.
I've provided a substitute implementation, hopefully it'll be acceptable. 
If not, any tips are welcome.

**Review by pop-simon — APPROVED** [review]

**Review by tsaskater — APPROVED** [review]

**Pull request merged**
