### PR TITLE
11 Drag-n-drop event

### LINKED ISSUE #11: Drag-n-drop event
At backend when the manager moves one event from date X to date Y, API call should update the event in the DB accordingly.

EST 3

### PR DESCRIPTION
**Pull request by akosgdcsi**
I think I've done it Dad, pls love me

### CODE REVIEW

**Review by pop-simon — CHANGES_REQUESTED** [review]
The `WorkEventRepo.Update(int oldKey, WorkEvent element)` method overrides the WorkEvent entity's **JobDescription** too but it should not. The fastest way to fix this is updating the `Task DnDEvent(int Id, DnDEventDTO newWorkEvent)` in **EventLogic.cs at line 73** to this:

`var result = mapper.Map<WorkEvent>(newWorkEvent);`
`var workEventInDb = await eventRepo.GetOne(Id);`
`result.JobDescription = workEventInDb.JobDescription;`
`await eventRepo.Update(Id, result);`

Another way to fix this is that you could create targeted `Update` methods in the **WorkEventRepo.cs**.

Otherwise it is nicely done! 💚

**Review by pop-simon — APPROVED** [review]

**Review by tsaskater — CHANGES_REQUESTED** [review]
If the corresponding event has assigned workers, you need to check for their schedule. 
Updating should only be allowed if it doesn't require a person (or more people) to be at two locations at the same time. When this happens, throwing a 405 status code would be adequate.
Otherwise, good job! 🎆

**Review by tsaskater — APPROVED** [review]
Not bad considering that you did it. 🥒🥒🥒🥒🥒🥒🥒🥒

**Review by luxz97 — APPROVED** [review]

**Comment by pop-simon** [comment]
I have rebased this branch to the development branch that contains the changes made by Zoli. Then I adapted the code to the changes and merged it with the remote branch. It looks ugly but worked for me.
**Please review the changes and let me know if something is missing or does not work properly!**
@tsaskater @luxz97 

edit: @akosgdcsi I could not add you as reviewer but please review the changes and comment your insights.

**Review by luxz97 — APPROVED** [review]

**Comment by akosgdcsi** [comment]
I've tested the exceptions and the time update and it's seems to be working fine. Thanks for the help ❤️ 🤗

**Review by tsaskater — APPROVED** [review]
Works and looks good ;)

**Pull request merged**
