### PR TITLE
5-Load-events-to-calendar-main-view

### LINKED ISSUE #4: Create calendar main view
(Find and) Create calendar view where the events can be displayed fetched from backend.

### PR DESCRIPTION
**Pull request by akosgdcsi**
pr

### CODE REVIEW

**Comment by rolandbogdan** [comment]
Ákos, please **don't** add me as a reviewer to your team's pulll requests. Thanks.

**Review by pop-simon — CHANGES_REQUESTED** [review]
I am missing the following:
- Create WorkEventDTO model in logic layer, the methods in CalendarEventLogic should return DTO models to the controllers 
- `CalendarEventLogic.GetDayEvents(int day)` should accept 366 as input and the proper maximum value validation is `day <= 366` **or** `day < 367`
- The if-else is unnecessary in `WorkEventRepo.GetOne(int key)`, you can just return the `entity` object

**Good job!**

**Comment by akosgdcsi** [comment]
> Create WorkEventDTO model in logic layer, the methods in CalendarEventLogic should return DTO models to the 
Done 

Done ✅

> CalendarEventLogic.GetDayEvents(int day) should accept 366 as input and the proper maximum value validation is day <= 366 or day < 367

Done ✅

> The if-else is unnecessary in WorkEventRepo.GetOne(int key), you can just return the entity object

Done ✅

**Review by pop-simon — APPROVED** [review]
🚀

**Review by tsaskater — APPROVED** [review]
Good job! 😎🐱‍🏍🐱‍🐉🛸

**Review by luxz97 — APPROVED** [review]

**Review by Levidaboi — APPROVED** [review]

**Pull request merged**
