### PR TITLE
Labels tab done 

### LINKED ISSUE #13: Create colorful labels and add to events
At frontend I'd like to be able to create labels and display them (with the label name visible inside!) on the events.

After a label was renamed or color changed, API call should be made to update it at backend/DB.

After a label was added to an event, API call should be made to update it at backend/DB.

EST 5

### PR DESCRIPTION
**Pull request by Levidaboi**
Meny Bug Sory For Inconviniens

### CODE REVIEW

**Comment by akosgdcsi** [comment]
kép

**Review by szdariusz — APPROVED** [review]
Looks good!
image

**Review by akosgdcsi — APPROVED** [review]
is it done?!?!!?!

**Review by pop-simon — CHANGES_REQUESTED** [review]
I think the CSS is not appropriate but that is a minor problem. The main issue with the implementation is that the color picker does not work. The color picker appears but I cannot choose a color nor enter a hex/rgb code when I would like to add a new label. If I want to edit an existing label then the color picker does not even appear. Besides that it works good I think 👌

**Review by pop-simon — APPROVED** [review]

**Pull request merged**
