### PR TITLE
Testing/5 load events to calendar

### LINKED ISSUE #4: Create calendar main view
(Find and) Create calendar view where the events can be displayed fetched from backend.

### PR DESCRIPTION
**Pull request by tubamark98**
I has't did complete the testing of thy CalenderEventLogic  and anon i do require thy help Architect.

### CODE REVIEW

**Review by pop-simon — CHANGES_REQUESTED** [review]
Could you create tests that check the methods with invalid parameter like irreal day number, null values etc.? It would be great to see if the exception handling also works properly. Checking for invalid input should be part of the testing in the future too.

Otherwise it is just fine 🔥

**Comment by tubamark98** [comment]
You got it king 👑, I'll get to it

**Review by pop-simon — APPROVED** [review]
Perfect! 🥇

**Review by tsaskater — APPROVED** [review]
Very nice! 👩‍🍳

**Pull request merged**
