### PR TITLE
2 loginlogout

### LINKED ISSUE #2: Login/logout
Create login and logout functionality at backend.
Add the 3 user roles such as.:
Admin,Manager,Worker
EST 3

### PR DESCRIPTION
**Pull request by luxz97**
Closes #2

### CODE REVIEW

**Review by tsaskater — CHANGES_REQUESTED** [review]
The WebApi project must reference ef tools to allow migrations,database updates.
On line 76 in the Startup.cs file add the Migrations assembly like this:
options.UseSqlServer(appsettingsConnectionString, b=>b.MigrationsAssembly("Wman.WebAPI")));
If you create an interface for AuthLogic why not use it for dependency injection?
Steps:
services.AddTransient<AuthLogic, AuthLogic>();
this should be replaced with:
services.AddScoped<IAuthLogic, AuthLogic>(); (I prefer scoped)
After that AuthController must use the interface injection in the constructor.
The signing key is sensitive data, must be read from the appsettings.json.
Appsettings.json is ignored in the gitignore file. Ignored files can be removed using the following commands:
git rm -r --cached .
git add .
git commit -m "Drop files from .gitignore"
Default user seeding does not work from the db context fix or remove that part.
The username and the email MUST be separated as properties. At the moment it’s the same for each registered user. Ákos can help with this part.
LoginDTO must contain the username property. A user must be able to login via their email OR username.
Please use async await in the logic as well. For example 
GetOne user should look like:
public async Task<WmanUser> GetOneUser(int id, string email)
…
return await userManager.Users.Where(x => x.Email == email).SingleOrDefaultAsync();
Please add validation to the input properties otherwise the database will contain invalid data.
The frontend MUST NEVER be able get or set invalid data.
Provide proper feedback on the endpoints. For example
return data why a login fails instead of just throwing an argument exception.
Feedback should look like: 404 „username/email does not exist” or 401 „Invalid password” 500 „something went wrong”. You need use status codes.
(This helps the frontend tremendously)
When there’s an object to return please use `ActionResult<T>`. This way if you return T it’s going to be an Ok result, otherwise you can return with other status codes with custom objects like return BadRequest(custom object). This provides more code readability.
Not auth realated:
User delete method does not work as intended and only provides a 200 status no matter the input please fix it.
User update method does not work.
IMO Dto models should contain DTO in their class names for readablity.
IMO You should use AddScoped instead of AddTransient. (not that big of a deal either way is good for our small app)

**Comment by luxz97** [comment]
Thanks for the feedback, will resolve most of these tomorrow late afternoon.

**Review by pop-simon — CHANGES_REQUESTED** [review]
I agree with Peti but I think there are more changes required.
Please consider doing the following:
- delete `Connection string.txt` because the DB connection string is in `appsettings.json`
- add to gitignore OR delete `*.mdf` and `*.ldf` files if you do not use them
- use relative path instead of direct path in **Wman.WebAPI.csproj** `<DocumentationFile>`

I suggest these not to litter the project nor create files in unexpected places (e.g. if I build the solution it creates a new folder on my machine's C: drive. Furthermore if someone does not have a drive named C: the build process will result in errors).

**Besides these problems it is good job!**

**Comment by luxz97** [comment]
I think I managed to touch on most of the issues, the detailed writeup was extremely helpful. 


> Default user seeding does not work from the db context fix or remove that part.

There isn't any user seeding in dbcontext yet, only default role seeding, but it worked for me.

> Appsettings.json is ignored in the gitignore file...

I left it there on purpose, to make testing easier, since it didn't contain sensitive information just yet. But if it's an issue, I can remove it.

**Review by pop-simon — APPROVED** [review]
Use unified naming conventions next time (e.g. use Pascal case when naming classes: `userDTO` -> `UserDTO`/`UserDto`). The `Converter.Convert(param)` methods should have different method names to ease readability in my opinion.
**I think these minor issues are acceptable now, everything else seems fine. Well done!**

**Review by tsaskater — CHANGES_REQUESTED** [review]
The signing key is sensitive data, must be read from the appsettings.json. 

I'm going to provide some corrections to my first response:
_„The username and the email MUST be separated as properties. At the moment, it’s the same for each registered user. Ákos can help with this part.”_

This part only applies to the db. That part is fixed. Good job. 😁

The issue is that you should not separate it in the LoginDTO.

_„LoginDTO must contain the username property. A user must be able to log in via their email OR username.”_

Correction:

The LoginDTO must contain **ONE** parameter called something like UserLogonName.

This parameter can be used via email **OR** username. The backend must recognize which was provided and act accordingly. At the moment, this endpoint needs 3 parameters for logging in, which is incorrect. The frontend is going to have two parameters for logging in:

**Field1: username/email and Field2: password**

Provide proper feedback on the endpoints. For example
return data why a login fails instead of just throwing an argument exception.
Feedback should look like: 404 „username/email does not exist” or 401 „Invalid password” 500 „something went wrong”. You need to use status codes.

(This helps the frontend tremendously)

At the moment no matter what if any of the fields are incorrect the only response is „Login failed”.
The frontend **CAN NOT** use that information for anything. If a login fails the frontend **MUST** know why it failed as mentioned before.

**Comment by luxz97** [comment]
> If a login fails the frontend MUST know why it failed as mentioned before.

I've made the changes as requested, but I'm not sure about this. IMO if a login fails, we should communicate as little information about why it failed, as possible, in case someone is trying to guess login details. Now, a malicious user can figure it out if he managed to get the loginName/pwd right.

**Comment by tsaskater** [comment]
> > If a login fails the frontend MUST know why it failed as mentioned before.
> 
> I've made the changes as requested, but I'm not sure about this. IMO if a login fails, we should communicate as little information about why it failed, as possible, in case someone is trying to guess login details. Now, a malicious user can figure it out if he managed to get the loginName/pwd right.

Conventionally, it's OK to return why a login fails. For example:
Try to log in to your Facebook with an incorrect password. As you can see, Facebook will provide details why your login failed.
If you try  to log in to an account with an incorrect username, Facebook is going to tell you that the user does not exist.
I can not recall any sites which does not have this feature implemented.
Guessing is usually solved by just limiting the request count for the particular IP and/or requiring a captcha.

**Review by tsaskater — APPROVED** [review]

**Review by akosgdcsi — APPROVED** [review]

**Pull request merged**
