### PR TITLE
Feature/18 display event details and modify them

### LINKED ISSUE #9: Feature/9-Create event
At frontend after click (+) button a new event can be added with the event details (eg. description, date from, date to, worker assign etc.)

EST 5

### PR DESCRIPTION
**Pull request by Levidaboi**
hali

### CODE REVIEW

**Review by tsaskater — DISMISSED** [review]
Works good! 🐻🐨

**Comment by akosgdcsi** [comment]
image

**Review by tamas-lengyel — APPROVED** [review]
Very good my boi 😘

**Comment by Levidaboi** [comment]
Event details update is done , we have a bug with the range picker though. If you want to update, you have to change the time range no matter what. It is a bug fix for the future, I have tried to fix it but failed miserably.

**Review by Broy1 — APPROVED** [review]
Bill Gates would be proud, solid job boys.

**Review by pop-simon — APPROVED** [review]
Good job! 👌

**Pull request merged**
