### PR TITLE
1 Project initialization PR

### PR DESCRIPTION
**Pull request by pop-simon**
Created the base projects and declared necessary information to the repository.

### CODE REVIEW

**Review by siposm — APPROVED** [review]
Looks good to me! 🙂 🔥

**Review by tsaskater — APPROVED** [review]
Swagger ✅
Testing references ✅
Db references ✅
React ✅
Nice Work

**Review by akosgdcsi — APPROVED** [review]
Nice Jób 😂👌🏼

**Review by Levidaboi — APPROVED** [review]
<3

**Review by szdariusz — COMMENTED** [review]
perfect

**Review by szdariusz — APPROVED** [review]

**Review by luxz97 — APPROVED** [review]

**Review by tubamark98 — COMMENTED** [review]
Looks good! =)

**Comment by siposm** [comment]
Nagyon szuper srácok! 👏🏻

**Pull request merged**
