### PR TITLE
notification with signalR and email

### LINKED ISSUE #17: Notify worker if assigned to event
At backend worker should be notified via email or something else (should be discussed later with PO) if he was assigned to or removed from an event.

EST 8

### PR DESCRIPTION
**Pull request by akosgdcsi**
update appsettings with the new parameters

### CODE REVIEW

**Review by rolandbogdan — COMMENTED** [review]
"fos" also known as "diarrhea" in english is a very inappropriate name for a commit. Please follow CoC for your commit messages.

**Comment by akosgdcsi** [comment]
> "fos" also known as "diarrhea" in english is a very inappropriate name for a commit. Please follow CoC for your commit messages.

fos stands for független objektív sajtó, so pls donate crypto for Wman and help fos to achive what its deserve 👨🏻

**Review by tsaskater — APPROVED** [review]
It is good it is signalR!
(And email)

**Review by luxz97 — APPROVED** [review]

**Review by pop-simon — APPROVED** [review]
New year gift

**Pull request merged**
